"""
    Code to insert the data collected from Yelp (stored in ./final.json) to DynamoDB. 
    The JSON file needed for inserting the same data to OpenSearch is also generated. 
    Each run of this file uploads 25 restaurants to DynamoDB and OpenSearch. 
    Files involved: 
        1. final.json -- stores ALL restaurant data (~5000 restaurants) returned from the Yelp API
        2. elastic.txt -- later converted to elastic.json; initially .txt format for easy file I/O, 
           .json format needed for insertion into OpenSearch
        3. yelp.json -- stores the 25 restaurants that we will upload to DynamoDB during this run
"""
import json
import os
from time import time

file = open("./final.json", "r") # restaurant data returned from the Yelp API 
data = json.load(file)
file.close()

aux = {"yelp-restaurants": []} # data to be inserted into DynamoDB yelp-restaurants

# initially, I intended an outer for loop with i incremented by 1 at a time
# however, an AWS CLI error prevented me from consecutively running the insertion command to the DynamoDB table
# data insertion from the AWS CLI is limited to 25 items at a time
# hence, I had to run the insertion command ~200 times, changing the value of i each time

i = 0 # up to at least 200 for a total of >= 5000 entries
for d in data[i*25:(i+1)*25]:
    # modifying the data to be inserted into DynamoDB yelp-restaurants
    copy = {
                "id": {"S": d["id"]},
                "name": {"S": d["name"]},
                "address": {"SS": d["location.display_address"]}, 
                "coordinates": {"NS": [str(d["coordinates.latitude"]), str(d["coordinates.longitude"])]},
                "review_count": {"N": str(d["review_count"])}, 
                "rating": {"N": str(d["rating"])}, 
                "zip": {"N": str(d["location.zip_code"])},
                "insertedAtTimestamp": {"N": str(time())} # storing the float generated by Python time.time()
            }
    aux["yelp-restaurants"].append({"PutRequest": {"Item": copy}})

    # generating the data to be inserted into OpenSearch (only the restaurant ID and cuisine)
    with open("./elastic.txt", "a", encoding='utf-8') as f: 
        json.dump(json.loads('{ "index" : { "_index": "restaurants", "_id" : "'+str(d["id"])+'" } }'), f, ensure_ascii=False)
        s = '{"cuisine": '+str(d["categories"])+'}'
        s = s.replace("\'", "\"")
        f.write("\n")
        json.dump(json.loads(s), f, ensure_ascii=False)
        f.write("\n")

file = open("./yelp.json", "w")
json.dump(aux, file)
file.close()

os.rename("./elastic.txt", "./elastic.json")
os.system("aws dynamodb batch-write-item --request-items file://yelp.json") # insert 25 items into DynamoDB
os.system("curl -XPOST -u 'kt:shreK@!$799' 'https://search-newdomain-ad5lvqbm3an6taybu34h6ptmv4.us-east-1.es.amazonaws.com/_bulk' --data-binary @elastic.json -H 'Content-Type: application/json'") 


# data format for insertion into OpenSearch
# { "index" : { "_index": "restaurants", "_id" : "zWem2SAbFc7lIYR2y9DE0g" } }
# {"cuisine": [{"alias": "dimsum", "title": "Dim Sum"}, {"alias": "cantonese", "title": "Cantonese"}, {"alias": "desserts", "title": "Desserts"}]}